name: Access Secrets

on:
  push:
    branches:
      - main

jobs:
  access-keys:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        SPOTIPY_CLIENT_ID: ${{ secrets.SPOTIPY_CLIENT_ID }}
        SPOTIPY_CLIENT_SECRET: ${{ secrets.SPOTIPY_CLIENT_SECRET }}
        SPOTIPY_REDIRECT_URI: ${{ secrets.SPOTIPY_REDIRECT_URI }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
